version: '3.7'
# Here we configure the Containers to run.
services:

  toolkit:
    image: proteinevolution/toolkit-docker:latest
    container_name: toolkit
    environment:
      - SUBMIT_MODE=LOCAL
      - SBT_OPTS=-Xms2G -Xmx4G -Xss2M
    #    stdin_open: true
    #    tty: true
    ports:
      - 1234:1234
      - 8080:8080
    volumes:
      - .:/toolkit
    #      Uncommenting following 3 lines will speed up sbt boot time significatnly providing you have GeoIP built locally
    #      - ~/.ivy2:/root/.ivy2
    #      - ~/.sbt:/root/.sbt
    #      - ~/.coursier:/root/.coursier
    links:
      - mongodb
    depends_on:
      - mongodb

  # The container for the MongoDB Database
  mongodb:
    image: mongo:4.0
    container_name: tk-mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
